# Generated by Django 3.2.8 on 2022-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, default=' ', max_length=200, verbose_name='分类描述'),
        ),
    ]
