# Generated by Django 3.2.8 on 2022-03-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '搜索'), (2, '最新文章'), (3, '热门文章'), (4, '最近评论'), (5, '文章归档'), (6, 'HTML')], default=1, verbose_name='展示类型'),
        ),
    ]
