# Generated by Django 3.2.8 on 2022-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_sidebar_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='游览量'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '搜索'), (2, '最新文章'), (3, '热门文章'), (4, '最近评论'), (5, '文章归档')], default=1, verbose_name='展示类型'),
        ),
    ]
