# Generated by Django 3.2.8 on 2022-03-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220306_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pv',
        ),
    ]
